### ISSUE TITLE
Contact User

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#15]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
Contact   User | User | The user can contact other users. | Discret and direct exchange from   information. | The user has to be logged   in.

**Comment by llandgraf** [comment]
Diese Funktion konnte leider nicht implementiert werden, da Accounts wegen unerwartetem Aufwand nicht implementier werden konnten.
