### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#2]
Erstellen Sie ein Anwendungsfalldiagramm für das Praktikumsprojekt und beschreiben Sie alle Anwendungsfälle gemäß der in der Vorlesung besprochenen Anwendungsfallbeschreibung (siehe Oestereich, Analyse und Design mit UML 2.1/3/5, S. 119 (8. Auflage), S. 126 (10. Auflage), S. 75 (11.Auflage)). Anwendungsfalldiagramm und Anwendungsfallbeschreibungen stellen Sie in das Wiki Ihres Github Repositories.

**Comment by costark** [comment]
Use Case Diagram wurde erstellt und anschließend wurde die finale Version in unser Wiki geladen. Die dazugehörige Description wurde fertiggestellt und muss nur noch in das Wiki gestellt werden.

**Comment by costark** [comment]
Use Case Diagram wurde nochmals verändert und schließlich nochmal neu in Wiki geladen. Die Description wurde ebenfalls teils geändert und in unser Wiki geladen.
