### ISSUE TITLE
Contact Admin

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#23]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
Contact   Admin | User | The user can contact the admin. | The user can request deleting   posts, inform the admin about unapropriate content or contact the admin with   any other problem related to the platform. | The user has to be logged   in.

**Comment by llandgraf** [comment]
Diese Funktion konnte leider nicht implementiert werden, da Accounts wegen unerwartetem Aufwand nicht implementier werden konnten.
