### ISSUE TITLE
Comment activity

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#24]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
Comment   Activity | Admin, User, Guest | The admin/user/guest can comment   on activites. | The admin/user/guest can discuss   about the posted activity. | The guest/user has to be logged in.

**Comment by llandgraf** [comment]
Diese Funktion konnte wegen unerwartetem Aufwand leider nicht implementiert werden.
