### ISSUE TITLE
Upvoting

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#25]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
Upvoting | User, Admin | The admin/user can like   activities. | Increasing popularity for   activites can be filtered and more easilie found. | The admin/user has to be   verified.

**Comment by llandgraf** [comment]
Diese Funktion konnte wegen unerwartetem Aufwand leider nicht implementiert werden.
