### ISSUE TITLE
Archive activity

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#26]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
Archive   activity | Admin | The admin can archive an   activity. | Knowledge base for later use.   Less information on the main platform. | The activity has to be closed and   must be older than 1 month.

**Comment by llandgraf** [comment]
Diese Funktion konnte wegen unerwartetem Aufwand leider nicht implementiert werden.
