### ISSUE TITLE
View archived activity

### ISSUE THREAD

**Issue by Wheedman** [sweIhm/sweiproject-tg2b-3#28]
name | role | description | use | acceptance criteria
-- | -- | -- | -- | --
View   archived activity | Admin, User, Guest | The admin/user/guest can view   archived activities | Get information for other   similar activities. | There are archived activities in   the archive.

**Comment by llandgraf** [comment]
Diese Funktion konnte leider nicht implementiert werden, da das Archievieren wegen unerwartetem Aufwand nicht implementier werden konnten.
