### ISSUE TITLE
Sprint 1 Wiki Page 

### ISSUE THREAD

**Issue by ptpl1511** [sweIhm/sweiproject-tg2b-3#29]
"Setzen Sie ein Sprint-Ziel (das Sprint Ziel heißt nicht 1. Release(!), geben Sie ein fachliches Ziel an). Erstellen sie eine Wiki-Seite für den 1. Sprint. Notieren Sie das Sprintziel und eine Zusammenfassung der wesentlichen User Stories auf der Wiki-Seite."

**Comment by ptpl1511** [comment]
Zusammenfassung Text + Verlinkungen erstellt

**Comment by costark** [comment]
das Sprintziel wurde ausformuliert. Die Zusammenfassung der wesentlichen Userstories, sowie das Sprintziel wurden auf die Wiki Page gestellt
